[BitTorrent]
Session\DefaultSavePath=/var/www/html/wd
Session\Port=51413
Session\Preallocation=true
Session\AppendExtension=false
Session\QueueingSystemEnabled=false
Session\GlobalMaxRatio=0
Session\MaxConnections=200
Session\MaxConnectionsPerTorrent=50
Session\DHTEnabled=true
Session\PeXEnabled=true
Session\LSDEnabled=false
Session\Encryption=1

[Preferences]
WebUI\Address=*
WebUI\Port=8080
WebUI\LocalHostAuth=false
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
Downloads\SavePath=/var/www/html/wd
Downloads\PreAllocation=true
General\Locale=en
